name: Release CLI-Rhythm

on:
  push:
    tags:
      - 'v*'  # Triggers only on version tags like v1.0.0

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install Linux audio build deps
        if: runner.os == 'Linux'          
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            libasound2-dev \
            libudev-dev \
            pkg-config

      - name: Build release
        run: cargo build --release

      - name: Rename binary
        run: |
          BINARY_PATH=target/release/cli-rhythm
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            mv $BINARY_PATH.exe cli-rhythm.exe
          else
            mv $BINARY_PATH cli-rhythm
          fi

      - name: Upload release binary
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cli-rhythm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
